const users = [
  {
    id: 1,
    name: '찌롱',
    title: '근면성실한',
    lv: '30',
    dream: '평범함이 모여 비범함이 된다.',
    activityList: [
      [
        { day: 'sun', count: 5 },
        { day: 'mon', count: 2 },
        { day: 'tue', count: 3 },
        { day: 'wed', count: 7 },
        { day: 'thu', count: 2 },
      ],
      [
        { day: 'sun', count: 1 },
        { day: 'mon', count: 1 },
        { day: 'tue', count: 2 },
        { day: 'wed', count: 1 },
        { day: 'thu', count: 2 },
      ],
      [
        { day: 'sun', count: 4 },
        { day: 'mon', count: 4 },
        { day: 'tue', count: 2 },
        { day: 'wed', count: 1 },
        { day: 'thu', count: 2 },
      ],
      [
        { day: 'sun', count: 3 },
        { day: 'mon', count: 4 },
        { day: 'tue', count: 3 },
        { day: 'wed', count: 5 },
        { day: 'thu', count: 3 },
      ],
      [
        { day: 'sun', count: 4 },
        { day: 'mon', count: 2 },
        { day: 'tue', count: 3 },
        { day: 'wed', count: 7 },
        { day: 'thu', count: 2 },
      ],
      [
        { day: 'sun', count: 4 },
        { day: 'mon', count: 3 },
        { day: 'tue', count: 7 },
        { day: 'wed', count: 1 },
        { day: 'thu', count: 0 },
      ],
      [
        { day: 'sun', count: 3 },
        { day: 'mon', count: 2 },
        { day: 'tue', count: 0 },
        { day: 'wed', count: 5 },
        { day: 'thu', count: 3 },
      ],
      [
        { day: 'sun', count: 0 },
        { day: 'mon', count: 2 },
        { day: 'tue', count: 1 },
        { day: 'wed', count: 5 },
        { day: 'thu', count: 3 },
      ],
      [
        { day: 'sun', count: 2 },
        { day: 'mon', count: 2 },
        { day: 'tue', count: 3 },
        { day: 'wed', count: 6 },
        { day: 'thu', count: 2 },
      ],
      [
        { day: 'sun', count: 4 },
        { day: 'mon', count: 3 },
        { day: 'tue', count: 3 },
        { day: 'wed', count: 7 },
        { day: 'thu', count: 8 },
      ],
      [
        { day: 'sun', count: 2 },
        { day: 'mon', count: 2 },
        { day: 'tue', count: 0 },
        { day: 'wed', count: 5 },
        { day: 'thu', count: 3 },
      ],
      [
        { day: 'sun', count: 0 },
        { day: 'mon', count: 2 },
        { day: 'tue', count: 3 },
        { day: 'wed', count: 3 },
        { day: 'thu', count: 8 },
      ],
      [
        { day: 'sun', count: 2 },
        { day: 'mon', count: 2 },
        { day: 'tue', count: 3 },
        { day: 'wed', count: 6 },
        { day: 'thu', count: 2 },
      ],
      [
        { day: 'sun', count: 4 },
        { day: 'mon', count: 3 },
        { day: 'tue', count: 3 },
        { day: 'wed', count: 7 },
        { day: 'thu', count: 8 },
      ],
      [
        { day: 'sun', count: 4 },
        { day: 'mon', count: 2 },
        { day: 'tue', count: 3 },
        { day: 'wed', count: 7 },
        { day: 'thu', count: 2 },
      ],
      [
        { day: 'sun', count: 4 },
        { day: 'mon', count: 3 },
        { day: 'tue', count: 7 },
        { day: 'wed', count: 1 },
        { day: 'thu', count: 0 },
      ],
      [
        { day: 'sun', count: 2 },
        { day: 'mon', count: 2 },
        { day: 'tue', count: 3 },
        { day: 'wed', count: 6 },
        { day: 'thu', count: 2 },
      ],
      [
        { day: 'sun', count: 5 },
        { day: 'mon', count: 2 },
        { day: 'tue', count: 3 },
        { day: 'wed', count: 7 },
        { day: 'thu', count: 2 },
      ],
      [
        { day: 'sun', count: 1 },
        { day: 'mon', count: 1 },
        { day: 'tue', count: 2 },
        { day: 'wed', count: 1 },
        { day: 'thu', count: 2 },
      ],
      [
        { day: 'sun', count: 0 },
        { day: 'mon', count: 2 },
        { day: 'tue', count: 1 },
        { day: 'wed', count: 5 },
        { day: 'thu', count: 3 },
      ],
    ],
  },
  {
    id: 2,
    name: '한스',
    title: '다정다감한',
    lv: '23',
    dream: '10kg 다이어트!',
    activityList: [
      [
        { day: 'sun', count: 5 },
        { day: 'mon', count: 2 },
        { day: 'tue', count: 3 },
        { day: 'wed', count: 7 },
        { day: 'thu', count: 2 },
        { day: 'fri', count: 3 },
        { day: 'sat', count: 2 },
      ],
      [
        { day: 'sun', count: 1 },
        { day: 'mon', count: 1 },
        { day: 'tue', count: 2 },
        { day: 'wed', count: 1 },
        { day: 'thu', count: 2 },
        { day: 'fri', count: 5 },
        { day: 'sat', count: 2 },
      ],
      [
        { day: 'sun', count: 4 },
        { day: 'mon', count: 4 },
        { day: 'tue', count: 2 },
        { day: 'wed', count: 1 },
        { day: 'thu', count: 2 },
        { day: 'fri', count: 3 },
        { day: 'sat', count: 3 },
      ],
      [
        { day: 'sun', count: 3 },
        { day: 'mon', count: 4 },
        { day: 'tue', count: 3 },
        { day: 'wed', count: 5 },
        { day: 'thu', count: 3 },
        { day: 'fri', count: 7 },
        { day: 'sat', count: 3 },
      ],
      [
        { day: 'sun', count: 4 },
        { day: 'mon', count: 2 },
        { day: 'tue', count: 3 },
        { day: 'wed', count: 7 },
        { day: 'thu', count: 2 },
        { day: 'fri', count: 0 },
        { day: 'sat', count: 4 },
      ],
      [
        { day: 'sun', count: 4 },
        { day: 'mon', count: 3 },
        { day: 'tue', count: 7 },
        { day: 'wed', count: 1 },
        { day: 'thu', count: 0 },
        { day: 'fri', count: 5 },
        { day: 'sat', count: 2 },
      ],
      [
        { day: 'sun', count: 3 },
        { day: 'mon', count: 2 },
        { day: 'tue', count: 0 },
        { day: 'wed', count: 5 },
        { day: 'thu', count: 3 },
        { day: 'fri', count: 0 },
        { day: 'sat', count: 3 },
      ],
      [
        { day: 'sun', count: 0 },
        { day: 'mon', count: 2 },
        { day: 'tue', count: 1 },
        { day: 'wed', count: 5 },
        { day: 'thu', count: 3 },
        { day: 'fri', count: 0 },
        { day: 'sat', count: 3 },
      ],
      [
        { day: 'sun', count: 5 },
        { day: 'mon', count: 2 },
        { day: 'tue', count: 3 },
        { day: 'wed', count: 7 },
        { day: 'thu', count: 2 },
        { day: 'fri', count: 3 },
        { day: 'sat', count: 2 },
      ],
      [
        { day: 'sun', count: 1 },
        { day: 'mon', count: 1 },
        { day: 'tue', count: 2 },
        { day: 'wed', count: 1 },
        { day: 'thu', count: 2 },
        { day: 'fri', count: 5 },
        { day: 'sat', count: 2 },
      ],
      [
        { day: 'sun', count: 4 },
        { day: 'mon', count: 4 },
        { day: 'tue', count: 2 },
        { day: 'wed', count: 1 },
        { day: 'thu', count: 2 },
        { day: 'fri', count: 3 },
        { day: 'sat', count: 3 },
      ],
      [
        { day: 'sun', count: 3 },
        { day: 'mon', count: 4 },
        { day: 'tue', count: 3 },
        { day: 'wed', count: 5 },
        { day: 'thu', count: 3 },
        { day: 'fri', count: 7 },
        { day: 'sat', count: 3 },
      ],
      [{ day: 'sun', count: 3 }],
    ],
  },
  {
    id: 3,
    name: '홍스',
    title: '평비 대표',
    lv: '42',
    dream: '평비 서비스 출시',
    activityList: [
      [
        { day: 'sun', count: 2 },
        { day: 'mon', count: 2 },
        { day: 'tue', count: 3 },
        { day: 'wed', count: 6 },
        { day: 'thu', count: 2 },
        { day: 'fri', count: 1 },
        { day: 'sat', count: 4 },
      ],
      [
        { day: 'sun', count: 4 },
        { day: 'mon', count: 3 },
        { day: 'tue', count: 3 },
        { day: 'wed', count: 7 },
        { day: 'thu', count: 8 },
        { day: 'fri', count: 11 },
        { day: 'sat', count: 2 },
      ],
      [
        { day: 'sun', count: 2 },
        { day: 'mon', count: 2 },
        { day: 'tue', count: 0 },
        { day: 'wed', count: 5 },
        { day: 'thu', count: 3 },
        { day: 'fri', count: 0 },
        { day: 'sat', count: 3 },
      ],
      [
        { day: 'sun', count: 0 },
        { day: 'mon', count: 2 },
        { day: 'tue', count: 3 },
        { day: 'wed', count: 3 },
        { day: 'thu', count: 8 },
        { day: 'fri', count: 0 },
        { day: 'sat', count: 3 },
      ],
      [
        { day: 'sun', count: 5 },
        { day: 'mon', count: 2 },
        { day: 'tue', count: 3 },
        { day: 'wed', count: 7 },
        { day: 'thu', count: 2 },
        { day: 'fri', count: 3 },
        { day: 'sat', count: 2 },
      ],
      [
        { day: 'sun', count: 1 },
        { day: 'mon', count: 1 },
        { day: 'tue', count: 2 },
        { day: 'wed', count: 1 },
        { day: 'thu', count: 2 },
        { day: 'fri', count: 5 },
        { day: 'sat', count: 2 },
      ],
      [
        { day: 'sun', count: 4 },
        { day: 'mon', count: 4 },
        { day: 'tue', count: 2 },
        { day: 'wed', count: 1 },
        { day: 'thu', count: 2 },
        { day: 'fri', count: 3 },
        { day: 'sat', count: 3 },
      ],
      [
        { day: 'sun', count: 3 },
        { day: 'mon', count: 4 },
        { day: 'tue', count: 3 },
        { day: 'wed', count: 5 },
        { day: 'thu', count: 3 },
        { day: 'fri', count: 7 },
        { day: 'sat', count: 3 },
      ],
      [
        { day: 'sun', count: 4 },
        { day: 'mon', count: 2 },
        { day: 'tue', count: 3 },
        { day: 'wed', count: 7 },
        { day: 'thu', count: 2 },
        { day: 'fri', count: 0 },
        { day: 'sat', count: 4 },
      ],
      [
        { day: 'sun', count: 4 },
        { day: 'mon', count: 3 },
        { day: 'tue', count: 7 },
        { day: 'wed', count: 1 },
        { day: 'thu', count: 0 },
        { day: 'fri', count: 5 },
        { day: 'sat', count: 2 },
      ],
      [
        { day: 'sun', count: 3 },
        { day: 'mon', count: 2 },
        { day: 'tue', count: 0 },
        { day: 'wed', count: 5 },
        { day: 'thu', count: 3 },
        { day: 'fri', count: 0 },
        { day: 'sat', count: 3 },
      ],
      [
        { day: 'sun', count: 0 },
        { day: 'mon', count: 2 },
        { day: 'tue', count: 1 },
        { day: 'wed', count: 5 },
        { day: 'thu', count: 3 },
        { day: 'fri', count: 0 },
        { day: 'sat', count: 3 },
      ],
      [{ day: 'sun', count: 3 }],
    ],
  },
];

export const getUser = (id) => {
  return users.find((user) => user.id === id);
};
