const users = [
  {
    id: 1,
    name: '찌롱',
    title: '근면성실한',
    lv: '30',
    dream: '평범함이 모여 비범함이 된다.',
    profileImage: '/images/penguin_and_me.png',
    backgroundImage:
      'https://post-phinf.pstatic.net/MjAxOTA2MDNfMTQ3/MDAxNTU5NTI5MTkxNTI1.rxCH-JM27rrnvatW0sGIC9GnEArQzCIDXBA9QGyTSNYg.oGXpWK7prD3Jq9VyI1Ta9h7wZ2fUGIvMx8hC5q2_oZ8g.JPEG/Summer_beach.jpg?type=w1200',
    activityList: [
      [{ count: 5 }, { count: 2 }, { count: 3 }, { count: 7 }, { count: 2 }],
      [{ count: 1 }, { count: 1 }, { count: 2 }, { count: 1 }, { count: 2 }],
      [{ count: 4 }, { count: 4 }, { count: 2 }, { count: 1 }, { count: 2 }],
      [{ count: 3 }, { count: 4 }, { count: 3 }, { count: 5 }, { count: 3 }],
      [{ count: 4 }, { count: 2 }, { count: 3 }, { count: 7 }, { count: 2 }],
      [{ count: 4 }, { count: 3 }, { count: 7 }, { count: 1 }, { count: 0 }],
      [{ count: 3 }, { count: 2 }, { count: 0 }, { count: 5 }, { count: 3 }],
      [{ count: 0 }, { count: 2 }, { count: 1 }, { count: 5 }, { count: 3 }],
      [{ count: 2 }, { count: 2 }, { count: 3 }, { count: 6 }, { count: 2 }],
      [{ count: 4 }, { count: 3 }, { count: 3 }, { count: 7 }, { count: 8 }],
      [{ count: 2 }, { count: 2 }, { count: 0 }, { count: 5 }, { count: 3 }],
      [{ count: 0 }, { count: 2 }, { count: 3 }, { count: 3 }, { count: 8 }],
      [{ count: 2 }, { count: 2 }, { count: 3 }, { count: 6 }, { count: 2 }],
      [{ count: 4 }, { count: 3 }, { count: 3 }, { count: 7 }, { count: 8 }],
      [{ count: 4 }, { count: 2 }, { count: 3 }, { count: 7 }, { count: 2 }],
      [{ count: 4 }, { count: 3 }, { count: 7 }, { count: 1 }, { count: 0 }],
      [{ count: 2 }, { count: 2 }, { count: 3 }, { count: 6 }, { count: 2 }],
      [{ count: 5 }, { count: 2 }, { count: 3 }, { count: 7 }, { count: 2 }],
      [{ count: 1 }, { count: 1 }, { count: 2 }, { count: 1 }, { count: 2 }],
      [{ count: 0 }, { count: 2 }, { count: 1 }, { count: 5 }, { count: 3 }],
    ],
  },
  {
    id: 2,
    name: '한스',
    title: '다정다감한',
    lv: '23',
    dream: '10kg 다이어트!',
    profileImage:
      'https://st.depositphotos.com/2069237/2950/i/950/depositphotos_29500311-stock-photo-running-man-male-runner-in.jpg',
    backgroundImage:
      'https://post-phinf.pstatic.net/MjAxOTA2MDNfMTQ3/MDAxNTU5NTI5MTkxNTI1.rxCH-JM27rrnvatW0sGIC9GnEArQzCIDXBA9QGyTSNYg.oGXpWK7prD3Jq9VyI1Ta9h7wZ2fUGIvMx8hC5q2_oZ8g.JPEG/Summer_beach.jpg?type=w1200',
    activityList: [
      [{ count: 5 }, { count: 2 }, { count: 3 }, { count: 7 }, { count: 2 }],
      [{ count: 1 }, { count: 1 }, { count: 2 }, { count: 1 }, { count: 2 }],
      [{ count: 4 }, { count: 4 }, { count: 2 }, { count: 1 }, { count: 2 }],
      [{ count: 3 }, { count: 4 }, { count: 3 }, { count: 5 }, { count: 3 }],
      [{ count: 4 }, { count: 2 }, { count: 3 }, { count: 7 }, { count: 2 }],
      [{ count: 4 }, { count: 3 }, { count: 7 }, { count: 1 }, { count: 0 }],
      [{ count: 3 }, { count: 2 }, { count: 0 }, { count: 5 }, { count: 3 }],
      [{ count: 0 }, { count: 2 }, { count: 1 }, { count: 5 }, { count: 3 }],
      [{ count: 2 }, { count: 2 }, { count: 3 }, { count: 6 }, { count: 2 }],
      [{ count: 4 }, { count: 3 }, { count: 3 }, { count: 7 }, { count: 8 }],
      [{ count: 2 }, { count: 2 }, { count: 0 }, { count: 5 }, { count: 3 }],
      [{ count: 0 }, { count: 2 }, { count: 3 }, { count: 3 }, { count: 8 }],
      [{ count: 2 }, { count: 2 }, { count: 3 }, { count: 6 }, { count: 2 }],
      [{ count: 4 }, { count: 3 }, { count: 3 }, { count: 7 }, { count: 8 }],
      [{ count: 4 }, { count: 2 }, { count: 3 }, { count: 7 }, { count: 2 }],
      [{ count: 4 }, { count: 3 }, { count: 7 }, { count: 1 }, { count: 0 }],
      [{ count: 2 }, { count: 2 }, { count: 3 }, { count: 6 }, { count: 2 }],
      [{ count: 5 }, { count: 2 }, { count: 3 }, { count: 7 }, { count: 2 }],
      [{ count: 1 }, { count: 1 }, { count: 2 }, { count: 1 }, { count: 2 }],
      [{ count: 0 }, { count: 2 }, { count: 1 }, { count: 5 }, { count: 3 }],
    ],
  },
  {
    id: 3,
    name: '홍스',
    title: '평비 대표',
    lv: '42',
    dream: '평비 서비스 출시',
    profileImage:
      'https://st.depositphotos.com/2069237/2950/i/950/depositphotos_29500311-stock-photo-running-man-male-runner-in.jpg',
    backgroundImage:
      'https://post-phinf.pstatic.net/MjAxOTA2MDNfMTQ3/MDAxNTU5NTI5MTkxNTI1.rxCH-JM27rrnvatW0sGIC9GnEArQzCIDXBA9QGyTSNYg.oGXpWK7prD3Jq9VyI1Ta9h7wZ2fUGIvMx8hC5q2_oZ8g.JPEG/Summer_beach.jpg?type=w1200',
    activityList: [
      [{ count: 5 }, { count: 2 }, { count: 3 }, { count: 7 }, { count: 2 }],
      [{ count: 1 }, { count: 1 }, { count: 2 }, { count: 1 }, { count: 2 }],
      [{ count: 4 }, { count: 4 }, { count: 2 }, { count: 1 }, { count: 2 }],
      [{ count: 3 }, { count: 4 }, { count: 3 }, { count: 5 }, { count: 3 }],
      [{ count: 4 }, { count: 2 }, { count: 3 }, { count: 7 }, { count: 2 }],
      [{ count: 4 }, { count: 3 }, { count: 7 }, { count: 1 }, { count: 0 }],
      [{ count: 3 }, { count: 2 }, { count: 0 }, { count: 5 }, { count: 3 }],
      [{ count: 0 }, { count: 2 }, { count: 1 }, { count: 5 }, { count: 3 }],
      [{ count: 2 }, { count: 2 }, { count: 3 }, { count: 6 }, { count: 2 }],
      [{ count: 4 }, { count: 3 }, { count: 3 }, { count: 7 }, { count: 8 }],
      [{ count: 2 }, { count: 2 }, { count: 0 }, { count: 5 }, { count: 3 }],
      [{ count: 0 }, { count: 2 }, { count: 3 }, { count: 3 }, { count: 8 }],
      [{ count: 2 }, { count: 2 }, { count: 3 }, { count: 6 }, { count: 2 }],
      [{ count: 4 }, { count: 3 }, { count: 3 }, { count: 7 }, { count: 8 }],
      [{ count: 4 }, { count: 2 }, { count: 3 }, { count: 7 }, { count: 2 }],
      [{ count: 4 }, { count: 3 }, { count: 7 }, { count: 1 }, { count: 0 }],
      [{ count: 2 }, { count: 2 }, { count: 3 }, { count: 6 }, { count: 2 }],
      [{ count: 5 }, { count: 2 }, { count: 3 }, { count: 7 }, { count: 2 }],
      [{ count: 1 }, { count: 1 }, { count: 2 }, { count: 1 }, { count: 2 }],
      [{ count: 0 }, { count: 2 }, { count: 1 }, { count: 5 }, { count: 3 }],
    ],
  },
];

export const getUser = (id) => {
  return users.find((user) => user.id === id);
};
